// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddMessageData, AddMessageErrors, AddMessageResponses, BenchmarkFlushData, BenchmarkFlushErrors, BenchmarkFlushResponses, BenchmarkJobStatusData, BenchmarkJobStatusErrors, BenchmarkJobStatusResponses, ContextPreRetrieveData, ContextPreRetrieveErrors, ContextPreRetrieveResponses, RecentMemoryData, RecentMemoryRawData, RecentMemoryRawResponses, RecentMemoryResponses, RetrieveMemoryData, RetrieveMemoryErrors, RetrieveMemoryRawData, RetrieveMemoryRawErrors, RetrieveMemoryRawResponses, RetrieveMemoryResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Add a message to a conversation
 */
export const addMessage = <ThrowOnError extends boolean = false>(options: Options<AddMessageData, ThrowOnError>) => (options.client ?? client).post<AddMessageResponses, AddMessageErrors, ThrowOnError>({
    url: '/api/v0/add_message',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const benchmarkFlush = <ThrowOnError extends boolean = false>(options: Options<BenchmarkFlushData, ThrowOnError>) => (options.client ?? client).post<BenchmarkFlushResponses, BenchmarkFlushErrors, ThrowOnError>({
    url: '/api/v0/benchmark/flush',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Query the processing status of a conversation's message queue.
 *
 * Used by the benchmark runner to poll until all ingested messages have been
 * processed into episodic memories before running evaluation.
 */
export const benchmarkJobStatus = <ThrowOnError extends boolean = false>(options: Options<BenchmarkJobStatusData, ThrowOnError>) => (options.client ?? client).get<BenchmarkJobStatusResponses, BenchmarkJobStatusErrors, ThrowOnError>({ url: '/api/v0/benchmark/job_status', ...options });

/**
 * Retrieve semantic memories as markdown for pre-retrieval context injection.
 * Semantic-only (facts + behavioral guidelines); episodic retrieval is left to LLM tool calls.
 * Does NOT record a pending review (no FSRS update triggered).
 */
export const contextPreRetrieve = <ThrowOnError extends boolean = false>(options: Options<ContextPreRetrieveData, ThrowOnError>) => (options.client ?? client).post<ContextPreRetrieveResponses, ContextPreRetrieveErrors, ThrowOnError>({
    url: '/api/v0/context_pre_retrieve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retrieve recent memories formatted as markdown for LLM consumption.
 * Returns only episode content, no full message details.
 */
export const recentMemory = <ThrowOnError extends boolean = false>(options: Options<RecentMemoryData, ThrowOnError>) => (options.client ?? client).post<RecentMemoryResponses, unknown, ThrowOnError>({
    url: '/api/v0/recent_memory',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retrieve recent memories in raw JSON format (newest first)
 */
export const recentMemoryRaw = <ThrowOnError extends boolean = false>(options: Options<RecentMemoryRawData, ThrowOnError>) => (options.client ?? client).post<RecentMemoryRawResponses, unknown, ThrowOnError>({
    url: '/api/v0/recent_memory/raw',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retrieve memories formatted as markdown for LLM consumption
 */
export const retrieveMemory = <ThrowOnError extends boolean = false>(options: Options<RetrieveMemoryData, ThrowOnError>) => (options.client ?? client).post<RetrieveMemoryResponses, RetrieveMemoryErrors, ThrowOnError>({
    url: '/api/v0/retrieve_memory',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retrieve memories in raw JSON format
 */
export const retrieveMemoryRaw = <ThrowOnError extends boolean = false>(options: Options<RetrieveMemoryRawData, ThrowOnError>) => (options.client ?? client).post<RetrieveMemoryRawResponses, RetrieveMemoryRawErrors, ThrowOnError>({
    url: '/api/v0/retrieve_memory/raw',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
