// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type AddMessage = {
    conversation_id: string;
    message: AddMessageMessage;
};

export type AddMessageMessage = {
    content: string;
    role: MessageRole;
    timestamp?: string | null;
};

export type AddMessageResult = {
    accepted: boolean;
    reason?: string | null;
};

export type BenchmarkFlush = {
    conversation_id: string;
};

export type BenchmarkFlushResult = {
    enqueued: boolean;
    reason: string;
};

export type BenchmarkJobStatus = {
    admissible_for_add: boolean;
    done: boolean;
    fence_active: boolean;
    flushable: boolean;
    messages_pending: number;
    predict_calibrate_jobs_active: number;
    segmentation_jobs_active: number;
};

export type ContextPreRetrieve = {
    /**
     * Optional category filter, e.g. "guideline", "preference"
     */
    category?: string | null;
    conversation_id: string;
    detail?: DetailLevel;
    query: string;
    query_embedding?: Array<number> | null;
    semantic_limit?: number;
};

export type DetailLevel = 'auto' | 'none' | 'low' | 'high';

export type EpisodicMemory = {
    consolidated_at?: string | null;
    content: string;
    conversation_id: string;
    created_at: string;
    difficulty: number;
    end_at: string;
    id: string;
    last_reviewed_at: string;
    messages: Array<Message>;
    stability: number;
    start_at: string;
    surprise: number;
    title: string;
};

export type EpisodicMemoryResult = EpisodicMemory & {
    /**
     * Final score (RRF score × FSRS retrievability)
     */
    score: number;
};

export type Message = {
    content: string;
    role: MessageRole;
    timestamp: string;
};

export type MessageRole = string;

export type RecentMemory = {
    /**
     * Conversation ID to filter memories by
     */
    conversation_id: string;
    /**
     * Limit to memories from the last N days (optional)
     * If not provided, returns the most recent memories up to `limit`
     */
    days_limit?: number | null;
    /**
     * Maximum memories to return (default: 10, max: 100)
     */
    limit?: number;
};

export type RetrieveMemory = {
    /**
     * Optional category filter, e.g. "guideline", "preference"
     */
    category?: string | null;
    /**
     * Conversation ID to filter memories by and associate pending review with
     */
    conversation_id: string;
    /**
     * Detail level: "auto", "none", "low", "high"
     */
    detail?: DetailLevel;
    /**
     * Maximum episodic memories to return (1-100)
     */
    episodic_limit?: number;
    /**
     * Search query text
     */
    query: string;
    /**
     * Optional precomputed embedding for the query
     */
    query_embedding?: Array<number> | null;
    /**
     * Maximum semantic memories to return
     */
    semantic_limit?: number;
};

export type RetrieveMemoryRawResult = {
    /**
     * Episodic memories with scores
     */
    episodic: Array<EpisodicMemoryResult>;
    /**
     * Semantic memories (known facts + behavioral guidelines)
     */
    semantic: Array<SemanticMemoryResult>;
};

export type SemanticMemory = {
    category: string;
    conversation_id: string;
    fact: string;
    id: string;
    invalid_at?: string | null;
    keywords: Array<string>;
    source_episodic_ids: Array<string>;
    valid_at: string;
};

export type SemanticMemoryResult = SemanticMemory & {
    /**
     * RRF score
     */
    score: number;
};

export type AddMessageData = {
    body: AddMessage;
    path?: never;
    query?: never;
    url: '/api/v0/add_message';
};

export type AddMessageErrors = {
    /**
     * Invalid request - message content cannot be empty
     */
    400: unknown;
    /**
     * Backpressured - message not accepted
     */
    429: AddMessageResult;
};

export type AddMessageError = AddMessageErrors[keyof AddMessageErrors];

export type AddMessageResponses = {
    /**
     * Message accepted
     */
    200: AddMessageResult;
};

export type AddMessageResponse = AddMessageResponses[keyof AddMessageResponses];

export type BenchmarkFlushData = {
    body: BenchmarkFlush;
    path?: never;
    query?: never;
    url: '/api/v0/benchmark/flush';
};

export type BenchmarkFlushErrors = {
    /**
     * Invalid request
     */
    400: unknown;
};

export type BenchmarkFlushResponses = {
    /**
     * Flush result
     */
    200: BenchmarkFlushResult;
};

export type BenchmarkFlushResponse = BenchmarkFlushResponses[keyof BenchmarkFlushResponses];

export type BenchmarkJobStatusData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Conversation ID to check
         */
        conversation_id: string;
    };
    url: '/api/v0/benchmark/job_status';
};

export type BenchmarkJobStatusErrors = {
    /**
     * Invalid request
     */
    400: unknown;
};

export type BenchmarkJobStatusResponses = {
    /**
     * Job status
     */
    200: BenchmarkJobStatus;
};

export type BenchmarkJobStatusResponse = BenchmarkJobStatusResponses[keyof BenchmarkJobStatusResponses];

export type ContextPreRetrieveData = {
    body: ContextPreRetrieve;
    path?: never;
    query?: never;
    url: '/api/v0/context_pre_retrieve';
};

export type ContextPreRetrieveErrors = {
    /**
     * Query cannot be empty
     */
    400: unknown;
};

export type ContextPreRetrieveResponses = {
    /**
     * Markdown context for system prompt injection
     */
    200: string;
};

export type ContextPreRetrieveResponse = ContextPreRetrieveResponses[keyof ContextPreRetrieveResponses];

export type RecentMemoryData = {
    body: RecentMemory;
    path?: never;
    query?: never;
    url: '/api/v0/recent_memory';
};

export type RecentMemoryResponses = {
    /**
     * Markdown formatted recent memories
     */
    200: string;
};

export type RecentMemoryResponse = RecentMemoryResponses[keyof RecentMemoryResponses];

export type RecentMemoryRawData = {
    body: RecentMemory;
    path?: never;
    query?: never;
    url: '/api/v0/recent_memory/raw';
};

export type RecentMemoryRawResponses = {
    /**
     * Recent episodic memories
     */
    200: Array<EpisodicMemory>;
};

export type RecentMemoryRawResponse = RecentMemoryRawResponses[keyof RecentMemoryRawResponses];

export type RetrieveMemoryData = {
    body: RetrieveMemory;
    path?: never;
    query?: never;
    url: '/api/v0/retrieve_memory';
};

export type RetrieveMemoryErrors = {
    /**
     * Query cannot be empty
     */
    400: unknown;
};

export type RetrieveMemoryResponses = {
    /**
     * Markdown formatted memory results
     */
    200: string;
};

export type RetrieveMemoryResponse = RetrieveMemoryResponses[keyof RetrieveMemoryResponses];

export type RetrieveMemoryRawData = {
    body: RetrieveMemory;
    path?: never;
    query?: never;
    url: '/api/v0/retrieve_memory/raw';
};

export type RetrieveMemoryRawErrors = {
    /**
     * Query cannot be empty
     */
    400: unknown;
};

export type RetrieveMemoryRawResponses = {
    /**
     * Semantic facts and episodic memories
     */
    200: RetrieveMemoryRawResult;
};

export type RetrieveMemoryRawResponse = RetrieveMemoryRawResponses[keyof RetrieveMemoryRawResponses];
